### ISSUE TITLE
Maintenance status/dependency bump request

### ISSUE THREAD

**Issue by shssoichiro** [abonander/multipart#128]
Greetings, I was auditing the dependency tree of one of my projects to try and reduce compile times, and found that this crate, which is used by the `warp` crate, has many outdated dependencies which is resulting in those dependencies needing to have multiple versions built (because other crates in the chain are using the latest versions). I then noticed that this crate hasn't been updated in the past 18 months. This brings me to ask a couple of questions:

1. Is this crate still being maintained?
1. If not, would you be willing to pass it on to a new maintainer?
1. If you're still passively maintaining it, would you be willing to update each of the dependencies to the latest version and perform a new release?

Thank you.

**Comment by abonander** [comment]
Warp should probably use `multipart-async` which I was in the process of updating last fall before work picked up and I haven't really had much time/energy to work on it since. I think I can _try_ to find some at least on that front.

I was debating replacing this crate's API entirely with `multipart-async`'s and dropping the latter as that's the direction the ecosystem is ultimately going (at least for the server side). I think Rocket may be the only sync API holdout left that's still being kept up to date.

However, blocking APIs are still useful at least on the client, and maybe for simpler server setups that don't necessarily need to support high throughput.

**Comment by abonander** [comment]
Published `0.17.0` and added maintenance note to README.
