### ISSUE TITLE
Missing field data when field contains multiple headers

### ISSUE THREAD

**Issue by nahumclements** [abonander/multipart#87]
I'm having trouble using the `multipart` crate to parse message bodies where a multipart field contains multiple headers. Fields that only have a Content-Disposition header are successfully parsed but fields that have multiple headers do not seem to be able to extract the field data. 

It's possible that I'm misusing `multipart` but I have a [minimal repro](https://github.com/abonander/multipart/files/1180110/bad_multipart_headers.tar.gz) that tries to show the problem. The repro attempts to parse a multipart body with two fields. Part 1 has a Content-Disposition header and a Content-Type header, whilst part 2 has just a Content-Disposition header. The project prints the name and data of each `MultipartField`, with the data for part 2 being printed successfully but the data for part 1 missing.
`cargo run` gives:
```
part1:
part2:
        Part 2 body
```

**Comment by abonander** [comment]
So this isn't because of multiple headers. When a `Content-Type` header is given for a field, regardless of the given MIME type, Multipart assumes that it is a file; `.as_text()` will return `None`. 

I'm not sure if I consider this a bug, for multiple reasons:

* A `Content-Type: text/plain` field will almost always have come from a text file with a filename, which the user might want to inspect or preserve, and returning `MultipartData::Text()` doesn't allow that.

* The file might be quite large and the user probably doesn't want to read it all into memory at once. Of course, if we're talking about DoS protection, an attacker could just send a massively large text field and Multipart will happily read that all into memory anyway; I should probably code in some sane limit there.

* The file might be in a different text encoding, which would need to be handled, and I'm not sure if I want to go down that rabbit hole right now. If the user wants to read the file to text then they can handle that themselves.

**Comment by little-bobby-tables** [comment]
I wonder if it's possible to expose `read_to_string()` from `PrivReadEntry`, so a field could be read like this:

```rust
let field_text = field.data.into_inner().read_to_string();
```

This can be documented as a low-level method, and it'd allow you to keep the higher-level `File` and `Text` abstractions while still letting the users handle edge cases themselves.

As for the security aspects, I don't think this should be the concern of the crate. A heads-up in the documentation is fine, an arbitrary limit is not. For public-facing endpoints, this can be handled much higher up the stack, at the reverse proxy/load balancer level.

**Comment by abonander** [comment]
I think I'd probably prefer to drop the distinction altogether, like I did in `multipart-async`, and yeah provide a `.read_to_string()` which should nicely override with `Read::read_to_string()`.

**Comment by abonander** [comment]
Actually it shouldn't be `.read_to_string()` because the precedence is always inherent -> trait if both can be resolved: https://play.rust-lang.org/?gist=fdff31ebe6ee948c746082edafe893eb&version=stable

So probably `.read_string()` instead.

**Comment by abonander** [comment]
Pretty sure this has been resolved for a while now, so closing.
