### ISSUE TITLE
Windows Text File Parsing Problem

### ISSUE THREAD

**Issue by jolhoeft** [abonander/multipart#93]
When uploading textfiles created on windows (CR+LF endings), a CR+LF at the end of the file will interact badly with BoundaryReader::read_to_boundary where is decides whether to back up two characters (https://github.com/abonander/multipart/blob/c5b407dd4d89166dfa86da9e387f3bd54da6600d/src/server/boundary.rs#L87-L97). When this happens the header parsing fails with a confusing "invalid header name" error:

2017-10-17T14:47:47.294530130-07:00 DEBUG multipart::server::field - string buf: "77\r\nContent-Disposition: form-data; name="comment"\r\n\r\ndd"
2017-10-17T14:47:47.294537891-07:00 ERROR virtua_rasa::middleware::wiki - multi threw error Error { repr: Custom(Custom { kind: InvalidData, error: Invalid("invalid header name") }) } for page `simple.svg'

**Comment by abonander** [comment]
I see the logic error, pretty simple fix though. Thanks for bringing this up.

**Comment by jolhoeft** [comment]
Excellent. I just tested a textarea, and not surprisingly, that can trigger this too.

**Comment by abonander** [comment]
Yeah it's anywhere you have two CR-LFs after a boundary. I guess I should treat this as two independent bugs:

* The `BoundaryReader` should not back up by more than one CRLF pair
* `parse_headers` should trim newlines before attempting to parse anything
    * because, to my understanding, this wouldn't be considered a malformed request; the advice is be strict in what you send but liberal in what you accept.

**Comment by therealbstern** [comment]
This also happens when you have trailing newlines without the `\r`.  I submitted a multipart textarea that ended with `\n\n` and multipart barfed.

**Comment by abonander** [comment]
@therealbstern can I see a raw request body for repro?

**Comment by abonander** [comment]
I ask because I think I was able to repro and fix the original issue here: https://github.com/abonander/multipart/blob/master/src/server/boundary.rs#L366

But when replacing the first CRLF with LFLF, the same repro doesn't fail the test, before or after the fix: https://github.com/abonander/multipart/blob/master/src/server/boundary.rs#L408

**Comment by therealbstern** [comment]
Sure, I'll get it to you tomorrow!

**Comment by therealbstern** [comment]
Here's the headers, lightly edited, but with all of the lengths correct.  This was captured by the "Live HTTP Headers" extension for Firefox.  If you need a tcpdump, let me know.  [double-nl.txt](https://github.com/abonander/multipart/files/1507980/double-nl.txt)

The field "source" is the one you want.  The data came from a `textarea` with the following contents:

   Just a test↵↵

Leading spaces are included for GitHub's rendering (the J is the character of the `textarea` content).  Also, ↵ means I hit return, causing the browser to insert a UNIX newline, rather than my typing the unicode character itself.

The bug can also be reproduced with:

    Just a test↲

but the headers I already captured have two newlines because I knew that triggered it.

If the GitHub upload mangles the headers, let me know and I'll email them to you.

**Comment by abonander** [comment]
It looks like the client converts all the newlines to CRLF because I'm only seeing `\r\n` pairs, which would have triggered the previously discussed bug if there was a trailing newline in any field. I can't figure how an `\n\n` would cause any problems because the code never looks for individual LF characters.

Does it still occur if you update to `0.13.4`? That has the fix in it.

**Comment by therealbstern** [comment]
We're taking a look at that right now and will get back to you shortly.  Thanks!

**Comment by jolhoeft** [comment]
I've tested under linux, and by uploading an SVG file with CRLF line endings and it is working fine. Once I get a chance to test on a windows machine, I think we'll be able to call this fixed.

**Comment by jolhoeft** [comment]
Working fine with windows too, closing.
