### ISSUE TITLE
Uploading .txt file from windows returns SavedData::Bytes and doesn't save file to disk

### ISSUE THREAD

**Issue by madmaxio** [abonander/multipart#99]
Is it expected behaviour?

**Comment by abonander** [comment]
Saving to disk is governed by `SaveBuilder::memory_threshold()`, currently defaulting to 10kB.

As for why it's saving as bytes and not as text, I presume it's because of the Windows default text encoding which is not strictly compatible with UTF-8. If it's pure ASCII then it should still decode, though.

**Comment by madmaxio** [comment]
Succeeded with 15KB text file, thx.
